alias more='batcat'
alias ee='mcedit'
# alias mc='. /usr/libexec/mc/mc-wrapper.sh'
alias -g G='| grep -i'
alias jf='journalctl -n1000 -f|fzf --tail 100000 --tac --no-sort --exact --wrap '
alias dni='dnf install'
alias l='eza -lahgF --group-directories-first --color-scale=size'
alias lt='eza -lahgF --group-directories-first --sort=modified --color-scale=size'
alias ll='eza -lahgF --extended --color-scale=size'
alias dfh='df -H'
