alias ee='mcedit'
# alias mc='. /usr/libexec/mc/mc-wrapper.sh'
alias -g G='| grep -i'
alias dni='dnf install'
alias l='eza -Flahg --icons --group-directories-first'
alias lt='eza -Flahg --icons --group-directories-first --sort=modified'
alias ll='eza -Flahg --extended'
alias dfh='df -H'